
name: Notify users based on issue labels

on:
  pull_request:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Hey 👋 the "{label}" was applied to this pull request. Would you be able to look at it please? Thank you 🙇' 
          recipients: |
            actions=@andymckay
