
name: Notify users based on issue labels

on:
  pull_request:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Hey 👋 the `{label}` label was applied to this pull request. This is just to let you know since it might be relevant and you might be to be help. Thanks 🙇'
          recipients: |
            actions=@andymckay
